// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMJxLZz0t2t1PmdEZUf_eMJlkCnebHy6Y',
    appId: '1:674482500876:android:a28efd933f85960861c529',
    messagingSenderId: '674482500876',
    projectId: 'ucsc-menu-app',
    databaseURL: 'https://ucsc-menu-app-default-rtdb.firebaseio.com',
    storageBucket: 'ucsc-menu-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZW3VR0kAo8bjpJjcv0mT1nkFvZWMJgU0',
    appId: '1:674482500876:ios:09b71ea2456ac5ef61c529',
    messagingSenderId: '674482500876',
    projectId: 'ucsc-menu-app',
    databaseURL: 'https://ucsc-menu-app-default-rtdb.firebaseio.com',
    storageBucket: 'ucsc-menu-app.appspot.com',
    iosClientId: '674482500876-chma7rkrojbliqvvr764ileirifl4hve.apps.googleusercontent.com',
    iosBundleId: 'com.example.menuApp',
  );
}
