# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # use_frameworks! # MIGHT NEED TO UNCOMMENT?
  use_modular_headers!
  #pods here i think
  # pod 'AppLovinSDK'
  # pod 'AppLovinMediationGoogleAdapter'
  # pod 'AppLovinMediationUnityAdsAdapter'
  # pod 'AppLovinMediationInMobiAdapter'
  pod 'Firebase/Analytics'
  # pod 'Google-Mobile-Ads-SDK'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

#pod 'IronSourceSDK'
#pod 'IronSourceSDK'
# pod 'IronSourceAdColonyAdapter'
# pod 'IronSourceAdMobAdapter'
# pod 'IronSourceFacebookAdapter'
# pod 'IronSourceUnityAdsAdapter'

# pod 'GoogleMobileAdsMediationAdColony'
# pod 'GoogleMobileAdsMediationIronSource'
# pod 'GoogleMobileAdsMediationFacebook'
# pod 'GoogleMobileAdsMediationUnity'
#from applovin
# Sources
# source 'https://cdn.cocoapods.org/'

# # Settings
# use_frameworks!
# inhibit_all_warnings!
# # Pods
# target 'YOUR_PROJECT_NAME' do
#     pod 'AppLovinSDK'
#     pod 'AppLovinMediationAdColonyAdapter'
#     pod 'AppLovinMediationGoogleAdapter'
#     pod 'AppLovinMediationIronSourceAdapter'
#     pod 'AppLovinMediationFacebookAdapter'
#     pod 'AppLovinMediationUnityAdsAdapter'
# end
